server:
  port: 8080
  
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/searchtest?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    username: ondaji
    password: alt846!@

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
        search:
          backend:
            type : lucene
            directory:
              root: C:/Temp
            analysis:
              configurer: class:com.chandler.analyzer.MyLuceneAnalysisConfigurer